### ISSUE TITLE
The arrow of the navigation overlaps the text in some cases

### ISSUE THREAD

**Issue by tatiNo5** [todinov/bulla#2]
The arrow of the navigation overlaps the text when it goes to the end of the line. See the attached screenshot 
![image](https://user-images.githubusercontent.com/16100377/88034706-bea8b500-cb49-11ea-9fe0-e04215519772.png)

**Comment by todinov** [comment]
Fixed with the latest commit (d90de908623ddd6fb26ac09a4cd4a7106aa1f8f1).
